import React, { useState } from 'react';
import { ExternalLink, Grid, Info } from 'lucide-react';
import { NATIONAL_TEXTILE_STATS } from '../data/nationalTextileData';

interface NationalOutcomeSectionProps {
  onOpenSources: () => void;
}

export const NationalOutcomeSection: React.FC<NationalOutcomeSectionProps> = ({ onOpenSources }) => {
  const [viewUnit, setViewUnit] = useState<'percent' | 'tonnes'>('percent');
  const [hoveredIdx, setHoveredIdx] = useState<number | null>(null);

  // 100 items representing the post-consumer volume
  // 55 are recovery (0 to 54), 45 are disposal (55 to 99)
  const totalGarments = 100;
  const recoveryCount = NATIONAL_TEXTILE_STATS.recoveryPct; // 55

  return (
    <section id="outcomes" className="py-20 sm:py-28 px-4 sm:px-6 lg:px-8 max-w-5xl mx-auto border-b border-[#D4D0C7]">
      {/* Section Eyebrow */}
      <div className="flex items-center justify-between mb-4">
        <span className="font-mono-tag text-xs uppercase tracking-widest text-[#6F6C66]">
          Step 08 / National Destination
        </span>
        <button
          onClick={onOpenSources}
          className="text-xs font-mono-tag text-[#191919] hover:underline flex items-center gap-1.5 px-2 py-0.5 rounded bg-[#FAF8F5] border border-[#D4D0C7]"
        >
          <span>MoT 2026 Table 4.2</span>
          <ExternalLink className="w-3 h-3" />
        </button>
      </div>

      <h2 className="font-serif-editorial text-4xl sm:text-5xl lg:text-6xl text-[#191919] mb-3 leading-tight">
        Where does post-consumer textile waste end up?
      </h2>
      <p className="text-lg sm:text-xl text-[#6F6C66] mb-8 max-w-2xl font-normal">
        Of the <strong>4.10 million tonnes</strong> generated by Indian households annually, here is the empirical destiny mapped by the Ministry of Textiles (2026):
      </p>

      {/* Unit Toggle and Legend Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6 pb-4 border-b border-[#D4D0C7]">
        {/* Legend */}
        <div className="flex items-center gap-4 text-xs font-mono-tag">
          <div className="flex items-center gap-2">
            <span className="w-3.5 h-3.5 rounded-xs bg-[#65785F]" />
            <span className="text-[#191919] font-bold">
              55% Recovered (2.255M Tonnes)
            </span>
          </div>
          <div className="flex items-center gap-2">
            <span className="w-3.5 h-3.5 rounded-xs bg-[#A64B32]" />
            <span className="text-[#191919] font-bold">
              45% Landfill/Incineration (1.845M Tonnes)
            </span>
          </div>
        </div>

        {/* Toggle Buttons */}
        <div className="inline-flex rounded-sm border border-[#191919] bg-[#FAF8F5] p-0.5 text-xs font-mono-tag">
          <button
            onClick={() => setViewUnit('percent')}
            className={`px-3 py-1 rounded-xs transition-colors ${
              viewUnit === 'percent'
                ? 'bg-[#191919] text-[#F2EFE8] font-bold'
                : 'text-[#6F6C66] hover:text-[#191919]'
            }`}
          >
            Show Percentage (%)
          </button>
          <button
            onClick={() => setViewUnit('tonnes')}
            className={`px-3 py-1 rounded-xs transition-colors ${
              viewUnit === 'tonnes'
                ? 'bg-[#191919] text-[#F2EFE8] font-bold'
                : 'text-[#6F6C66] hover:text-[#191919]'
            }`}
          >
            Show Approx. Tonnes
          </button>
        </div>
      </div>

      {/* 100-Garment Pictogram Card */}
      <div className="bg-[#FAF8F5] border border-[#191919] rounded-sm p-6 sm:p-8 mb-8 shadow-xs">
        <div className="flex items-center justify-between mb-4">
          <span className="font-mono-tag text-xs uppercase text-[#6F6C66] flex items-center gap-1.5 font-bold">
            <Grid className="w-3.5 h-3.5" />
            100-Garment Pictogram Grid
          </span>
          <span className="font-mono-tag text-xs text-[#6F6C66]">
            1 icon = {viewUnit === 'percent' ? '1% of national volume' : '≈ 41,000 Tonnes (41 KTPA)'}
          </span>
        </div>

        {/* 10x10 Grid */}
        <div className="grid grid-cols-10 gap-2 sm:gap-3 p-4 bg-white border border-[#D4D0C7] rounded-xs mb-4">
          {Array.from({ length: totalGarments }).map((_, idx) => {
            const isRecovery = idx < recoveryCount;
            const isHovered = hoveredIdx === idx;
            return (
              <button
                key={idx}
                onMouseEnter={() => setHoveredIdx(idx)}
                onMouseLeave={() => setHoveredIdx(null)}
                className={`aspect-square rounded-xs flex items-center justify-center transition-transform ${
                  isHovered ? 'scale-125 z-10 ring-2 ring-[#191919]' : ''
                } ${
                  isRecovery
                    ? 'bg-[#65785F]/20 text-[#65785F] border border-[#65785F]/40 hover:bg-[#65785F] hover:text-white'
                    : 'bg-[#A64B32]/20 text-[#A64B32] border border-[#A64B32]/40 hover:bg-[#A64B32] hover:text-white'
                }`}
                title={isRecovery ? 'Recovery pathway (Reuse/Recycle/Downcycle)' : 'Disposal pathway (Incineration/Landfill)'}
                aria-label={`Garment ${idx + 1}: ${isRecovery ? 'Recovered' : 'Disposed'}`}
              >
                {/* Minimal T-shirt glyph */}
                <svg viewBox="0 0 24 24" className="w-4 h-4 fill-current">
                  <path d="M20.38 3.46 16 2a4 4 0 0 1-8 0L3.62 3.46a2 2 0 0 0-1.34 2.23l.58 3.47a1 1 0 0 0 .99.84H6v10c0 1.1.9 2 2 2h8a2 2 0 0 0 2-2V10h2.15a1 1 0 0 0 .99-.84l.58-3.47a2 2 0 0 0-1.34-2.23z" />
                </svg>
              </button>
            );
          })}
        </div>

        {/* Dynamic Context Tooltip */}
        <div className="h-10 flex items-center justify-between text-xs font-mono-tag">
          {hoveredIdx !== null ? (
            <span className="text-[#191919]">
              Garment #{hoveredIdx + 1}:{' '}
              <strong className={hoveredIdx < recoveryCount ? 'text-[#65785F]' : 'text-[#A64B32]'}>
                {hoveredIdx < recoveryCount
                  ? 'Channelled to Recovery (Reuse, Shredding, or Downcycling)'
                  : 'Lost to Disposal (Open Dumpsite, Landfill, or Burning)'}
              </strong>
            </span>
          ) : (
            <span className="text-[#6F6C66] flex items-center gap-1.5">
              <Info className="w-3.5 h-3.5" />
              Hover or tap any garment icon to see what it represents
            </span>
          )}
        </div>
      </div>

      {/* Summary Stat Comparison */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="p-6 bg-[#FAF8F5] border-l-4 border-[#65785F] rounded-sm">
          <span className="font-mono-tag text-xs uppercase text-[#65785F] font-bold block mb-1">
            Recovery Channels
          </span>
          <div className="flex items-baseline gap-2 mb-2">
            <span className="font-serif-editorial text-4xl font-bold text-[#191919]">
              {viewUnit === 'percent' ? '55%' : '2.255M'}
            </span>
            <span className="font-mono-tag text-xs text-[#6F6C66]">
              {viewUnit === 'percent' ? '(2,255 KTPA)' : 'Tonnes/year'}
            </span>
          </div>
          <p className="text-xs text-[#191919] leading-relaxed">
            Preserved through informal re-wear, domestic rag repurposing, and mechanical shredding into relief blankets and carpet yarn.
          </p>
        </div>

        <div className="p-6 bg-[#FAF8F5] border-l-4 border-[#A64B32] rounded-sm">
          <span className="font-mono-tag text-xs uppercase text-[#A64B32] font-bold block mb-1">
            Permanent Loss (Disposal)
          </span>
          <div className="flex items-baseline gap-2 mb-2">
            <span className="font-serif-editorial text-4xl font-bold text-[#191919]">
              {viewUnit === 'percent' ? '45%' : '1.845M'}
            </span>
            <span className="font-mono-tag text-xs text-[#6F6C66]">
              {viewUnit === 'percent' ? '(1,845 KTPA)' : 'Tonnes/year'}
            </span>
          </div>
          <p className="text-xs text-[#191919] leading-relaxed">
            Almost half of all clothing discarded by Indian citizens ends up buried in unlined municipal dumpsites or incinerated without energy recovery.
          </p>
        </div>
      </div>
    </section>
  );
};
